"""pybasil - A VBScript parser and interpreter in Python."""

from .ast_nodes import (
    ASTNode,
    Program,
    NumberLiteral,
    StringLiteral,
    BooleanLiteral,
    NothingLiteral,
    EmptyLiteral,
    NullLiteral,
    Identifier,
    BinaryExpression,
    UnaryExpression,
    ComparisonExpression,
    MemberAccess,
    FunctionCall,
    MethodCall,
    NewExpression,
    ArrayAccess,
    DimVariable,
    DimStatement,
    AssignmentStatement,
    SetStatement,
    CallStatement,
    ExpressionStatement,
    IfStatement,
    ElseIfClause,
    ElseClause,
    CaseClause,
    CaseElseClause,
    SelectCaseStatement,
    ForStatement,
    ForEachStatement,
    WhileStatement,
    DoLoopStatement,
    LoopCondition,
    ExitStatement,
    SubStatement,
    FunctionStatement,
    Parameter,
    BinaryOp,
    UnaryOp,
    ComparisonOp,
    ExitType,
    LoopConditionType,
    ReDimStatement,
    EraseStatement,
)
from .parser import VBScriptParser, parse
from .runtime import (
    Environment,
    WScriptObject,
    VBScriptError,
    VBScriptNothing,
    VBScriptEmpty,
    VBScriptNull,
    VBScriptArray,
    VBScriptDictionary,
    NOTHING,
    EMPTY,
    NULL,
    Procedure,
)
from .interpreter import (
    Interpreter,
    run,
)

__version__ = '0.1.0'

__all__ = [
    # AST Nodes
    'ASTNode',
    'Program',
    'NumberLiteral',
    'StringLiteral',
    'BooleanLiteral',
    'NothingLiteral',
    'EmptyLiteral',
    'NullLiteral',
    'Identifier',
    'BinaryExpression',
    'UnaryExpression',
    'ComparisonExpression',
    'MemberAccess',
    'FunctionCall',
    'MethodCall',
    'NewExpression',
    'ArrayAccess',
    'DimVariable',
    'DimStatement',
    'AssignmentStatement',
    'SetStatement',
    'CallStatement',
    'ExpressionStatement',
    # Control Flow AST Nodes
    'IfStatement',
    'ElseIfClause',
    'ElseClause',
    'CaseClause',
    'CaseElseClause',
    'SelectCaseStatement',
    'ForStatement',
    'ForEachStatement',
    'WhileStatement',
    'DoLoopStatement',
    'LoopCondition',
    'ExitStatement',
    # Procedure AST Nodes
    'SubStatement',
    'FunctionStatement',
    'Parameter',
    # Array AST Nodes
    'ReDimStatement',
    'EraseStatement',
    # Enums
    'BinaryOp',
    'UnaryOp',
    'ComparisonOp',
    'ExitType',
    'LoopConditionType',
    # Parser
    'VBScriptParser',
    'parse',
    # Interpreter
    'Interpreter',
    'Environment',
    'WScriptObject',
    'VBScriptError',
    'VBScriptNothing',
    'VBScriptEmpty',
    'VBScriptNull',
    'VBScriptArray',
    'VBScriptDictionary',
    'NOTHING',
    'EMPTY',
    'NULL',
    'Procedure',
    'run',
]
