"""pybasil - A VBScript parser and interpreter in Python."""

from .ast_nodes import (
    ASTNode,
    Program,
    NumberLiteral,
    StringLiteral,
    BooleanLiteral,
    NothingLiteral,
    EmptyLiteral,
    NullLiteral,
    Identifier,
    BinaryExpression,
    UnaryExpression,
    ComparisonExpression,
    MemberAccess,
    FunctionCall,
    MethodCall,
    NewExpression,
    DimStatement,
    AssignmentStatement,
    SetStatement,
    CallStatement,
    ExpressionStatement,
    IfStatement,
    ElseIfClause,
    ElseClause,
    ForStatement,
    WhileStatement,
    DoLoopStatement,
    LoopCondition,
    ExitStatement,
    SubStatement,
    FunctionStatement,
    Parameter,
    BinaryOp,
    UnaryOp,
    ComparisonOp,
    ExitType,
    LoopConditionType,
)
from .parser import VBScriptParser, parse
from .interpreter import (
    Interpreter,
    Environment,
    WScriptObject,
    VBScriptError,
    VBScriptNothing,
    VBScriptEmpty,
    VBScriptNull,
    NOTHING,
    EMPTY,
    NULL,
    Procedure,
    run,
)

__version__ = "0.1.0"

__all__ = [
    # AST Nodes
    "ASTNode",
    "Program",
    "NumberLiteral",
    "StringLiteral",
    "BooleanLiteral",
    "NothingLiteral",
    "EmptyLiteral",
    "NullLiteral",
    "Identifier",
    "BinaryExpression",
    "UnaryExpression",
    "ComparisonExpression",
    "MemberAccess",
    "FunctionCall",
    "MethodCall",
    "NewExpression",
    "DimStatement",
    "AssignmentStatement",
    "SetStatement",
    "CallStatement",
    "ExpressionStatement",
    # Control Flow AST Nodes
    "IfStatement",
    "ElseIfClause",
    "ElseClause",
    "ForStatement",
    "WhileStatement",
    "DoLoopStatement",
    "LoopCondition",
    "ExitStatement",
    # Procedure AST Nodes
    "SubStatement",
    "FunctionStatement",
    "Parameter",
    # Enums
    "BinaryOp",
    "UnaryOp",
    "ComparisonOp",
    "ExitType",
    "LoopConditionType",
    # Parser
    "VBScriptParser",
    "parse",
    # Interpreter
    "Interpreter",
    "Environment",
    "WScriptObject",
    "VBScriptError",
    "VBScriptNothing",
    "VBScriptEmpty",
    "VBScriptNull",
    "NOTHING",
    "EMPTY",
    "NULL",
    "Procedure",
    "run",
]
